image: node:lts

stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - pnpm lint

test:
  stage: test
  script:
    - pnpm test

build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - artifacts/
      - abis/
