image: node:lts

stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - artifacts/
      - abis/
