image: node:lts

stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  image: node:lts
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml

lint:
  stage: lint
  script:
    - pnpm lint

test:
  stage: test
  script:
    - pnpm test

build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - artifacts/
      - abis/
